name: Sample Book Application Workflow



on:
  push:
    branches: ["main", "github_workflows"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Print step name
      run: echo "Building oh node application is starting..."
    - name: Install all dependencies
      run: npm install
  deploy-dev:
    runs-on: self-hosted
    needs: [build]
    steps:
    - uses: actions/checkout@v4
    - name: Print step name
      run: echo "Deployment to DEV has started..."
    - name: Install all dependencies
      run: npm install
    - name: Delete existing pm2 service || exit 0
      run: pm2 delete "books-DEV"
    - name: DRun sample-book-app pm2 service
      run: pm2 start -n \"books-DEV\" index.js -- 1010
  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'mtararujs/api-automation'
        ref: 'books_tests'
    - name: Print step name
      run: echo "Testing BOOKS test set on DEV has started..."
    - name: Install all dependencies
      run: npm instal
    - name: Run API test_set
      run: npm run BOOKS BOOKS_DEV

    #  echo "Testing ${test_set} test set on ${environment} has started.."
    #  git branch: 'books_tests', poll: false, url: 'https://github.com/mtararujs/api-automation.git'
    #  bat "npm install"
    #  bat "npm run ${test_set} ${test_set}_${environment}"

  deploy-stg:
    runs-on: self-hosted
    needs: [test-dev]
    steps:
    - uses: actions/checkout@v4
    - name: Print step name
      run: echo "Deployment to STG has started..."


  test-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
    - uses: actions/checkout@v4
    - name: Print step name
      run: echo "Testing BOOKS test set on STG has started..."
  deploy-prod:
    runs-on: self-hosted
    needs: [test-stg]
    steps:
    - uses: actions/checkout@v4
    - name: Print step name
      run: echo "Deployment to PRD has started..."
  test-prod:
    runs-on: self-hosted
    needs: [deploy-prod]
    steps:
    - uses: actions/checkout@v4
    - name: Print step name
      run: echo "Testing BOOKS test set on PRD has started..."
